Rubocop
mohammadali-bacha/THP-2.0 pull request #9
Opened 2018-07-04 21:39 UTC by mohammadali-bacha

2018-07-04 21:54 UTC, zaratan requested changes

2018-07-04 21:54 UTC, denispasin commented on rubocop.yml
> +# Relaxed.Ruby.Style
Ce fichier ne devrait pas exister

2018-07-04 21:54 UTC, denispasin commented on .rubocop_todo.yml
> +# This configuration was generated by
Pourquoi ? Un `rubocop -a` ne fixait pas tout ?

2018-07-04 21:54 UTC, denispasin commented on .rubocop-https---relaxed-ruby-style-rubocop-yml
> +# Relaxed.Ruby.Style
Si tu le DL en http, tu devrais enlever la version https

2018-07-05 09:07 UTC, mohammadali-bacha commented on .rubocop_todo.yml
> +# This configuration was generated by
ah non c'etait au debut , quand j'ai suivi la doc

2018-07-05 09:07 UTC, mohammadali-bacha commented on .rubocop-https---relaxed-ruby-style-rubocop-yml
> +# Relaxed.Ruby.Style
c'est bon

2018-07-05 09:09 UTC, mohammadali-bacha commented on .rubocop_todo.yml
> +# This configuration was generated by
du coup je fais quoi ?

2018-07-05 09:09 UTC, mohammadali-bacha commented on rubocop.yml
> +# Relaxed.Ruby.Style
done

2018-07-05 11:31 UTC, denispasin commented on .rubocop_todo.yml
> +# This configuration was generated by
Supprime le fichier et lance un `rubocop -a` :)

2018-07-05 15:29 UTC, merged